// src/routes/$workoutId/reorder.tsx
import { Navbar, Page, PageHeader } from "$lib/components";
import { db, type WorkoutExercise } from "$lib/db";
import { Button } from "$lib/eb";
import { arraymove } from "$lib/utils";
import { CaretDownIcon, CaretUpIcon, CheckIcon } from "@phosphor-icons/react";
import { createFileRoute } from "@tanstack/react-router";
import { useLiveQuery } from "dexie-react-hooks";
import { useState } from "react";

export const Route = createFileRoute("/$workoutId/reorder")({
  component: Reorder,
});

function Reorder() {
  const { workoutId } = Route.useParams();

  const workout = useLiveQuery(() => db.workouts.get(workoutId), [workoutId]);
  const workoutExercises = useLiveQuery(
    () =>
      db.workoutExercises.where("workoutId").equals(workoutId).sortBy("order"),
    [workoutId],
  );

  // Local order while editing; null means "same as saved"
  const [ordered, setOrdered] = useState<WorkoutExercise[] | null>(null);
  const exercises = ordered ?? workoutExercises ?? [];

  const changed =
    ordered !== null &&
    ordered.some(
      (exercise, idx) => exercise.id !== workoutExercises?.[idx]?.id,
    );

  function move(from: number, to: number) {
    const next = [...exercises];
    arraymove(next, from, to);
    setOrdered(next);
  }

  async function saveChanges() {
    if (!ordered || !changed) return;

    await db.transaction("rw", [db.workoutExercises], async (tx) => {
      for (let i = 0; i < ordered.length; i++) {
        await tx.workoutExercises.update(ordered[i].id, { order: i + 1 });
      }
    });
    setOrdered(null);
  }

  return (
    <Page>
      <PageHeader title={workout?.name} />
      <ol className="divide-muted divide-y">
        {exercises.map((exercise, idx) => (
          <li
            key={exercise.id}
            className="flex items-center justify-between gap-4 py-4"
            style={{ viewTransitionName: `reorder-${exercise.id}` }}
          >
            <span className="text-base font-semibold">{exercise.name}</span>
            <span className="flex gap-2">
              <Button
                iconOnly
                aria-label={`Move ${exercise.name} up`}
                disabled={idx === 0}
                onClick={() => move(idx, idx - 1)}
              >
                <CaretUpIcon />
              </Button>
              <Button
                iconOnly
                aria-label={`Move ${exercise.name} down`}
                disabled={idx === exercises.length - 1}
                onClick={() => move(idx, idx + 1)}
              >
                <CaretDownIcon />
              </Button>
            </span>
          </li>
        ))}
      </ol>

      <Navbar backHref={`/${workoutId}`}>
        <Button
          variant="primary"
          className="flex-1"
          disabled={!changed}
          icon={<CheckIcon />}
          iconPosition="end"
          onClick={saveChanges}
        >
          Save changes
        </Button>
      </Navbar>
    </Page>
  );
}

// src/routes/[workoutId]/reorder/+page.svelte
<script lang="ts">
  import {
    Button,
    Navbar,
    Page,
    PageHeader,
    NavbarButton,
  } from "$lib/components";
  import { page } from "$app/state";
  import { flip } from "svelte/animate";
  import { CaretDownIcon, CaretUpIcon, CheckIcon } from "phosphor-svelte";
  import { liveQuery } from "dexie";
  import { db } from "$lib/db";
  import { arraymove } from "$lib/utils";

  const workout = liveQuery(() => db.workouts.get(page.params.workoutId));

  const workoutExercises = liveQuery(() =>
    db.workoutExercises
      .where("workoutId")
      .equals(page.params.workoutId)
      .sortBy("order"),
  );

  let orderedExercises = $state(
    $workoutExercises ? [...$workoutExercises] : [],
  );

  let changed = $derived.by(() => {
    if (!$workoutExercises) return false;
    return (
      JSON.stringify($workoutExercises) !== JSON.stringify(orderedExercises)
    );
  });

  $effect(() => {
    orderedExercises = $workoutExercises ? [...$workoutExercises] : [];
  });

  async function saveChanges() {
    if (!changed) return;

    await db.transaction("rw", [db.workoutExercises], async (tx) => {
      for (let i = 0; i < orderedExercises.length; i++) {
        await tx.workoutExercises.update(orderedExercises[i].id, {
          order: i + 1,
        });
      }
    });
  }
</script>

<Page>
  <PageHeader title={$workout?.name} />
  <ol class="divide-divide divide-y">
    {#each orderedExercises as exercise, idx (exercise.id)}
      <li
        animate:flip={{ duration: 300 }}
        class="flex items-center justify-between px-4 py-5 font-bold"
      >
        {exercise.name}
        <div class="flex gap-3">
          <Button
            disabled={idx === 0}
            variant="outline"
            type="button"
            onclick={() => arraymove(orderedExercises, idx, idx - 1)}
          >
            <CaretUpIcon />
          </Button>
          <Button
            variant="outline"
            disabled={idx === $workoutExercises?.length - 1}
            type="button"
            onclick={() => arraymove(orderedExercises, idx, idx + 1)}
          >
            <CaretDownIcon />
          </Button>
        </div>
      </li>
    {/each}
  </ol>
  <Navbar backHref="/{page.params.workoutId}">
    <NavbarButton class="w-full" disabled={!changed} onclick={saveChanges}>
      Save changes <CheckIcon />
    </NavbarButton>
  </Navbar>
</Page>
