// src/lib/components/features/settings/SettingsDrawer.svelte
<script lang="ts">
  import { Drawer, Field, Label, WeightUnitSelect } from "$lib/components";
  import { getDefaultWeightUnit, setDefaultWeightUnit } from "$lib/utils";
  import type { ComponentProps } from "svelte";
  type Props = Omit<ComponentProps<typeof Drawer>, "title">;

  let { open = $bindable(), ...props }: Props = $props();

  let defaultUnit = $state(getDefaultWeightUnit());
</script>

<Drawer bind:open title="Settings" {...props}>
  <Field>
    <Label for="defaultUnit">Default weight unit</Label>
    <WeightUnitSelect
      value={defaultUnit}
      onchange={(value) => {
        setDefaultWeightUnit(value);
        defaultUnit = value;
      }}
    />
  </Field>
</Drawer>

// src/lib/components/features/settings/SettingsDrawer.tsx
import { getDefaultWeightUnit, setDefaultWeightUnit } from "$lib/utils";
import { useState } from "react";
import { Sheet, WeightUnitSelect } from "../../shared";

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

export function SettingsDrawer({ open, onOpenChange }: Props) {
  const [defaultUnit, setDefaultUnit] = useState(getDefaultWeightUnit);

  return (
    <Sheet open={open} onOpenChange={onOpenChange} title="Settings">
      <WeightUnitSelect
        label="Default weight unit"
        value={defaultUnit}
        onValueChange={(unit) => {
          setDefaultWeightUnit(unit);
          setDefaultUnit(unit);
        }}
      />
    </Sheet>
  );
}
