// src/routes/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { SportsJogging } from "$lib/assets";
  import {
    WorkoutCard,
    EmptyMessage,
    Pressable,
    Page,
    Input,
    PageHeader,
    Button,
    InputDialog,
  } from "$lib/components";
  import { IconCirclePlus } from "@tabler/icons-svelte";
  import { createWorkout } from "$lib/mutations";
  import { onMount } from "svelte";

  const { data } = $props();

  let showIllustration = $state(false);
  let showModal = $state(false);

  const handleCreateWorkout = async (name: string) => {
    if (!name) return;
    const newId = await createWorkout(name);
    if (newId) {
      goto(`/${newId}/exercises?complete=true`);
    }
  };

  onMount(() => {
    showIllustration = data.workouts.length === 0;
  });
</script>

<Page>
  <PageHeader title="Workouts">
    {#snippet right()}
      <button onclick={() => (showModal = true)}>
        <IconCirclePlus color="var(--primary)" size={24} />
      </button>
    {/snippet}
  </PageHeader>
  <section>
    {#if data.workouts.length > 0}
      {#each data.workouts as workout}
        <Pressable href={`/${workout.id}`}>
          <WorkoutCard
            workoutName={workout.name}
            exercises={workout.exercises.map((e) => e.name)}
          />
        </Pressable>
      {/each}
    {:else}
      <EmptyMessage
        header="No workouts yet."
        message="Tap the plus button to add one."
      />
    {/if}
  </section>
  {#if showIllustration}
    <SportsJogging />
  {/if}
</Page>
<InputDialog
  title="Create a workout"
  onSubmit={handleCreateWorkout}
  submitText="Create"
  placeholder="e.g. Upper Body"
  bind:open={showModal}
/>

<style>
  section {
    display: flex;
    flex-direction: column;
    gap: var(--size-4);
    overflow: scroll;
  }
</style>

// src/routes/index.tsx
import { SportsJogging } from "$lib/assets";
import {
  EmptyMessage,
  InputDialog,
  Navbar,
  Page,
  PageHeader,
  SettingsDrawer,
  WorkoutCard,
} from "$lib/components";
import { db, getWorkoutsInfo } from "$lib/db";
import { Button } from "$lib/eb";
import { ClockCounterClockwiseIcon, GearIcon, PlusIcon } from "@phosphor-icons/react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useLiveQuery } from "dexie-react-hooks";
import { useState } from "react";

export const Route = createFileRoute("/")({
  component: Home,
});

function Home() {
  const navigate = useNavigate();
  const [showCreate, setShowCreate] = useState(false);
  const [showSettings, setShowSettings] = useState(false);

  const workouts = useLiveQuery(() => getWorkoutsInfo());

  async function createWorkout(name: string) {
    if (!name) return;
    const newId = await db.workouts.add({ name });
    navigate({
      to: "/$workoutId/exercises",
      params: { workoutId: newId },
      search: { complete: true },
    });
  }

  return (
    <Page>
      <PageHeader
        title="Workouts"
        actions={
          <Button
            variant="ghost"
            iconOnly
            aria-label="Create a workout"
            onClick={() => setShowCreate(true)}
          >
            <PlusIcon />
          </Button>
        }
      />
      <section className="flex flex-col gap-4">
        {workouts?.length === 0 ? (
          <>
            <EmptyMessage header="No workouts yet." message="Tap the plus button to add one." />
            <SportsJogging />
          </>
        ) : (
          workouts?.map((workout) => (
            <Link key={workout.id} to="/$workoutId" params={{ workoutId: workout.id }}>
              <WorkoutCard workoutName={workout.name} exercises={workout.exercises} />
            </Link>
          ))
        )}
      </section>

      <Navbar>
        <Button
          className="flex-1"
          icon={<ClockCounterClockwiseIcon />}
          iconPosition="end"
          onClick={() => navigate({ to: "/history" })}
        >
          History
        </Button>
        <Button iconOnly aria-label="Settings" onClick={() => setShowSettings(true)}>
          <GearIcon />
        </Button>
      </Navbar>

      <SettingsDrawer open={showSettings} onOpenChange={setShowSettings} />
      <InputDialog
        open={showCreate}
        onOpenChange={setShowCreate}
        title="Create a workout"
        submitText="Create"
        placeholder="e.g. Upper body"
        onSubmit={createWorkout}
      />
    </Page>
  );
}
