// src/routes/history/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { page } from "$app/state";
  import { BusinessClipboard } from "$lib/assets";
  import {
    EmptyMessage,
    HistoryCard,
    Navbar,
    Page,
    PageHeader,
  } from "$lib/components";
  import { db } from "$lib/db";
  import { calculateTonnagePerAttribute } from "$lib/utils";
  import { SpinnerIcon } from "phosphor-svelte";
  import { liveQuery } from "dexie";

  let history = liveQuery(() =>
    db.history.orderBy("startTime").reverse().toArray(),
  );
  let successSets = liveQuery(() => {
    return db.historySets.filter((set) => set.isSuccess).toArray();
  });

  let tonnage: Map<string, number> = $derived(
    calculateTonnagePerAttribute($successSets || [], (set) => set.historyId),
  );
</script>

<Page>
  <PageHeader title="History" />
  <section class="space-y-8">
    {#if $history}
      {#if $history.length === 0}
        <EmptyMessage
          header="No history yet."
          message="Past workout details will appear here."
        />
        <BusinessClipboard />
      {/if}
      {#each $history as item (item.id)}
        <HistoryCard
          onclick={() => {
            goto(`/${item.workoutId}/history/${item.id}?from=${page.url}`);
          }}
          workoutName={item.workoutName}
          startTime={item.startTime}
          endTime={item.endTime}
          tonnage={tonnage.get(item.id) || 0}
        />
      {/each}
    {:else}
      <SpinnerIcon class="mx-auto mt-30 animate-spin " />
    {/if}
  </section>
  <Navbar backHref="/" />
</Page>

// src/routes/_tabs/history.tsx
import { BusinessClipboard } from "$lib/assets";
import { EmptyMessage, HistoryCard, Page, PageHeader } from "$lib/components";
import { db } from "$lib/db";
import { calculateTonnagePerAttribute } from "$lib/utils";
import { SpinnerIcon } from "@phosphor-icons/react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useLiveQuery } from "dexie-react-hooks";
import { useMemo } from "react";

export const Route = createFileRoute("/_tabs/history")({
  component: History,
});

function History() {
  const history = useLiveQuery(() => db.history.orderBy("startTime").reverse().toArray());
  const successSets = useLiveQuery(() => db.historySets.filter((set) => set.isSuccess).toArray());

  const tonnage = useMemo(
    () => calculateTonnagePerAttribute(successSets ?? [], (s) => s.historyId),
    [successSets],
  );

  return (
    <Page>
      <PageHeader title="History" />
      {!history ? (
        <SpinnerIcon className="mx-auto mt-30 animate-spin" />
      ) : history.length === 0 ? (
        <>
          <EmptyMessage header="No history yet." message="Past workout details will appear here." />
          <BusinessClipboard />
        </>
      ) : (
        <section className="flex flex-col gap-4">
          {history.map((item) => (
            <Link
              key={item.id}
              to="/$workoutId/history/$historyId"
              params={{ workoutId: item.workoutId, historyId: item.id }}
              search={{ from: "/history" }}
            >
              <HistoryCard
                workoutName={item.workoutName}
                startTime={item.startTime}
                endTime={item.endTime}
                tonnage={tonnage.get(item.id) ?? 0}
              />
            </Link>
          ))}
        </section>
      )}
    </Page>
  );
}
