// src/ActiveExerciseSet.svelte
<script lang="ts">
  import Button from "./Button.svelte";
  import { Checkmark } from "$lib/icons";

    type Props = {
        setId: number;
        reps: number;
        weight: number;
        isComplete: boolean;
        onToggleComplete?: (isComplete: boolean) => void;
        onRepsChange?: (reps: number) => void;
        onWeightChange?: (weight: number) => void;
    }

    let { reps, weight, isComplete, setId, onRepsChange, onToggleComplete, onWeightChange}: Props = $props();
</script>

<div>
    <section>
        <label for={`reps-${setId}`}>
            Reps
        </label>
        <input id={`reps-${setId}`} inputmode="numeric" min={0} disabled={isComplete} type="number" defaultValue={reps} onchange={(e) => onRepsChange?.(Number(e.currentTarget.value))}  />
    </section>

    <section>
        <label for={`weight-${setId}`}>
            Weight <span class="unit">(lbs)</span>
        </label>
        <input id={`weight-${setId}`} inputmode="numeric" min={0} disabled={isComplete} type="number" defaultValue={weight} onchange={(e)=> onWeightChange?.(Number(e.currentTarget.value))} />
    </section>

    <section class="checkbox">
        <Button rounded="full" variant={isComplete ? "primary" : "outline"} onclick={() => onToggleComplete?.(!isComplete)}>
            {#if isComplete}
                <Checkmark />
            {/if}
        </Button>
    </section>    
</div>


<style>
    div {
        display: grid;
        grid-template-columns: repeat(5, minmax(0, 1fr));
        gap: var(--size-2);
        margin: var(--size-2) 0;
    }

    label {
        font-weight: var(--font-weight-5);
        display: flex;
        gap: var(--size-2);
        .unit {
            color: hsl(var(--magnolia-hsl) / 70%);
        }
    }

    section {
        display: flex;
        flex-direction: column;
        gap: var(--size-2);
        margin: var(--size-2) 0;
        grid-column: span 2 / span 2;
    }

    section.checkbox {
        grid-column: span 1 / span 1;
        padding-top: var(--size-5);
        align-items: center;
    }

    input {
        display: flex;
        background-color: transparent;
        color: var(--magnolia);
        font-size: var(--font-size-3);
        font-weight: var(--font-weight-7);
        border: 1px solid hsl(var(--magnolia-hsl) / 50%);
    }
</style>

// src/lib/components/features/activity/ActiveExerciseSet.tsx
import type { WeightUnit } from "$lib/db";
import { Field, Input, ToggleButton } from "$lib/eb";
import { CheckIcon } from "@phosphor-icons/react";

type Props = {
  setIndex: number;
  reps: number;
  weight: number;
  weightUnit: WeightUnit;
  isComplete: boolean;
  onToggleComplete: (isComplete: boolean) => void;
  onRepsChange: (reps: number) => void;
  onWeightChange: (weight: number) => void;
};

function numberHandler(onValue: (value: number) => void) {
  return (event: React.ChangeEvent<HTMLInputElement>) => {
    const { value } = event.currentTarget;
    if (value !== "" && !Number.isNaN(Number(value))) onValue(Number(value));
  };
}

export function ActiveExerciseSet({
  setIndex,
  reps,
  weight,
  weightUnit,
  isComplete,
  onToggleComplete,
  onRepsChange,
  onWeightChange,
}: Props) {
  const setNumber = setIndex + 1;

  return (
    <section className="flex items-end gap-3" aria-label={`Set ${setNumber}`}>
      <span className="text-muted-foreground w-5 shrink-0 pb-2.5 font-semibold tabular-nums">
        {setNumber}
      </span>
      <Field className="flex-1" disabled={isComplete}>
        <Field.Label>Reps</Field.Label>
        <Input
          type="number"
          inputMode="numeric"
          min={0}
          defaultValue={reps}
          onChange={numberHandler(onRepsChange)}
        />
      </Field>
      <Field className="flex-1" disabled={isComplete}>
        <Field.Label>Weight ({weightUnit})</Field.Label>
        <Input
          type="number"
          inputMode="decimal"
          min={0}
          step={0.5}
          defaultValue={weight}
          onChange={numberHandler(onWeightChange)}
        />
      </Field>
      <ToggleButton
        tone="primary"
        aria-label={`Set ${setNumber} complete`}
        pressed={isComplete}
        onPressedChange={onToggleComplete}
      >
        <CheckIcon />
      </ToggleButton>
    </section>
  );
}
