// src/lib/components/features/activity/ActiveExerciseSet.svelte
<script lang="ts">
  import type { WeightUnit } from "$lib/db";
  import { Button, Input } from "../../ui";
  import { CheckIcon } from "phosphor-svelte";

  type Props = {
    setIndex: number;
    reps: number;
    weight: number;
    isComplete: boolean;
    weightUnit: WeightUnit;
    onToggleComplete?: (isComplete: boolean) => void;
    onRepsChange?: (reps: number) => void;
    onWeightChange?: (weight: number) => void;
  };

  let {
    reps,
    weight,
    weightUnit,
    isComplete,
    setIndex,
    onRepsChange,
    onToggleComplete,
    onWeightChange,
  }: Props = $props();
</script>

<section class="grid grid-cols-8 gap-2 pr-2 pl-1">
  <div
    class="text-muted-foreground col-span-3 text-xs tracking-wider uppercase"
  >
    <label for={`reps-${setIndex}`}>Reps</label>
  </div>
  <div
    class="text-muted-foreground col-span-3 text-xs tracking-wider uppercase"
  >
    <label for={`weight-${setIndex}`}>
      Weight <span class="unit">({weightUnit})</span>
    </label>
  </div>
  <div class="col-span-2"></div>
  <Input
    class="col-span-3"
    id={`reps-${setIndex}`}
    inputmode="numeric"
    min={0}
    disabled={isComplete}
    type="number"
    defaultValue={reps}
    onchange={(e) => onRepsChange?.(Number(e.currentTarget.value))}
  />
  <Input
    class="col-span-4"
    id={`weight-${setIndex}`}
    inputmode="decimal"
    min={0}
    disabled={isComplete}
    type="number"
    defaultValue={weight}
    onchange={(e) => onWeightChange?.(Number(e.currentTarget.value))}
  />
  <Button
    class="col-span-1"
    variant={isComplete ? "primary" : "outline"}
    onclick={() => onToggleComplete?.(!isComplete)}
  >
    {#if isComplete}
      <CheckIcon />
    {/if}
  </Button>
</section>

// src/lib/components/features/activity/ActiveExerciseSet.tsx
import type { WeightUnit } from "$lib/db";
import { Field, Input, ToggleButton } from "$lib/eb";
import { CheckIcon } from "@phosphor-icons/react";

type Props = {
  setIndex: number;
  reps: number;
  weight: number;
  weightUnit: WeightUnit;
  isComplete: boolean;
  onToggleComplete: (isComplete: boolean) => void;
  onRepsChange: (reps: number) => void;
  onWeightChange: (weight: number) => void;
};

function numberHandler(onValue: (value: number) => void) {
  return (event: React.ChangeEvent<HTMLInputElement>) => {
    const { value } = event.currentTarget;
    if (value !== "" && !Number.isNaN(Number(value))) onValue(Number(value));
  };
}

export function ActiveExerciseSet({
  setIndex,
  reps,
  weight,
  weightUnit,
  isComplete,
  onToggleComplete,
  onRepsChange,
  onWeightChange,
}: Props) {
  const setNumber = setIndex + 1;

  return (
    <section className="flex items-end gap-3" aria-label={`Set ${setNumber}`}>
      <span className="text-muted-foreground w-5 shrink-0 pb-2.5 font-semibold tabular-nums">
        {setNumber}
      </span>
      <Field className="flex-1" disabled={isComplete}>
        <Field.Label>Reps</Field.Label>
        <Input
          type="number"
          inputMode="numeric"
          min={0}
          defaultValue={reps}
          onChange={numberHandler(onRepsChange)}
        />
      </Field>
      <Field className="flex-1" disabled={isComplete}>
        <Field.Label>Weight ({weightUnit})</Field.Label>
        <Input
          type="number"
          inputMode="decimal"
          min={0}
          step={0.5}
          defaultValue={weight}
          onChange={numberHandler(onWeightChange)}
        />
      </Field>
      <ToggleButton
        tone="primary"
        aria-label={`Set ${setNumber} complete`}
        pressed={isComplete}
        onPressedChange={onToggleComplete}
      >
        <CheckIcon />
      </ToggleButton>
    </section>
  );
}
