// src/lib/components/features/activity/ActiveExerciseCard.svelte
<script lang="ts">
  import {
    CheckCircleIcon,
    CircleIcon,
    MinusCircleIcon,
  } from "phosphor-svelte";

  type Props = {
    exerciseName: string;
    setCount: number;
    completeSets: number;
    isComplete: boolean;
  };

  let { exerciseName, setCount, isComplete, completeSets }: Props = $props();
</script>

<div class="border-border flex items-center gap-4 rounded-sm border p-2">
  <div>
    {#if isComplete}
      <CheckCircleIcon color="var(--color-accent)" />
    {:else if completeSets > 0}
      <MinusCircleIcon color="var(--color-accent)" />
    {:else}
      <CircleIcon class="text-muted-foreground" />
    {/if}
  </div>
  <div class="grid gap-2">
    <h3 class="text-lg font-bold">{exerciseName}</h3>
    <p class="text-muted-foreground text-sm">
      {completeSets} / {setCount} sets
    </p>
  </div>
</div>

<style>
</style>

// src/lib/components/features/activity/ActiveExerciseCard.tsx
import { Card } from "$lib/eb";
import {
  CheckCircleIcon,
  CircleIcon,
  MinusCircleIcon,
} from "@phosphor-icons/react";

type Props = {
  exerciseName: string;
  setCount: number;
  completeSets: number;
};

export function ActiveExerciseCard({
  exerciseName,
  setCount,
  completeSets,
}: Props) {
  const isComplete = setCount > 0 && completeSets === setCount;

  return (
    <Card className="flex-row items-center">
      <span className="shrink-0 pl-5">
        {isComplete ? (
          <CheckCircleIcon weight="fill" className="text-accent" />
        ) : completeSets > 0 ? (
          <MinusCircleIcon className="text-accent" />
        ) : (
          <CircleIcon className="text-muted-foreground" />
        )}
      </span>
      <Card.Header className="flex-1 pb-5">
        <Card.Title>{exerciseName}</Card.Title>
        <span className="text-muted-foreground">
          {completeSets} of {setCount} {setCount === 1 ? "set" : "sets"}
        </span>
      </Card.Header>
    </Card>
  );
}
