// src/lib/components/ExerciseItem.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";

  type Props = HTMLAttributes<HTMLDivElement> & {
    name: string;
    sets: number;
    reps: number;
    weight: number;
  };

  let { name, sets, reps, weight, ...props }: Props = $props();
</script>

<div class="container" {...props}>
  <div class="weight">
    <span>{weight}</span>
    <span class="weight-unit">lbs</span>
  </div>
  <div class="details">
    <span class="name">{name}</span>
    <span>{sets} sets, {reps} reps</span>
  </div>
</div>

<style>
  .container {
    display: flex;
    align-items: center;
    gap: var(--size-3);
    padding: var(--size-3) var(--size-2);
    width: 100%;
  }

  .weight {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    border: 2px solid var(--primary);
    border-radius: var(--radius-round);
    min-width: var(--size-8);
    min-height: var(--size-8);
    color: var(--foreground);
    font-weight: var(--font-weight-6);
    font-size: small;
    font-size: var(--font-size-2);
    text-align: center;
  }

  .weight-unit {
    font-size: var(--font-size-0);
  }

  .details {
    display: grid;
    gap: var(--size-2);
  }

  .name {
    font-weight: var(--font-weight-6);
    font-size: var(--font-size-2);
  }
</style>

// src/lib/components/features/workout/ExerciseItem.tsx
import type { WeightUnit } from "$lib/db";

type Props = {
  name: string;
  sets: number;
  reps: number;
  weight: number;
  weightUnit: WeightUnit;
  onClick?: () => void;
};

export function ExerciseItem({ name, sets, reps, weight, weightUnit, onClick }: Props) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="flex w-full cursor-pointer items-center gap-4 py-2 text-left"
    >
      <span className="border-accent flex size-14 shrink-0 flex-col items-center justify-center rounded-full border">
        <span className="font-semibold">{weight}</span>
        <span className="text-muted-foreground text-xs">{weightUnit}</span>
      </span>
      <span className="flex min-w-0 flex-1 flex-col gap-1">
        <span className="text-xl font-semibold">{name}</span>
        <span className="text-muted-foreground">
          {sets} sets, {reps} reps
        </span>
      </span>
    </button>
  );
}
