// src/lib/components/features/workout/ExerciseItem.tsx
import type { WeightUnit } from "$lib/db";

type Props = {
  name: string;
  sets: number;
  reps: number;
  weight: number;
  weightUnit: WeightUnit;
  onClick?: () => void;
};

export function ExerciseItem({ name, sets, reps, weight, weightUnit, onClick }: Props) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="flex w-full cursor-pointer items-center gap-4 py-2 text-left"
    >
      <span className="border-accent flex size-14 shrink-0 flex-col items-center justify-center rounded-full border">
        <span className="font-semibold">{weight}</span>
        <span className="text-muted-foreground text-xs">{weightUnit}</span>
      </span>
      <span className="flex min-w-0 flex-1 flex-col gap-1">
        <span className="text-xl font-semibold">{name}</span>
        <span className="text-muted-foreground">
          {sets} sets, {reps} reps
        </span>
      </span>
    </button>
  );
}

// src/lib/components/features/workout/ExerciseItem.svelte
<script lang="ts">
  import type { WeightUnit } from "$lib/db";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = HTMLAttributes<HTMLDivElement> & {
    name: string;
    sets: number;
    reps: number;
    weight: number;
    weightUnit: WeightUnit;
  };

  let { name, sets, reps, weight, weightUnit, ...props }: Props = $props();
</script>

<div class="flex w-full items-center gap-4 p-2" {...props}>
  <div
    class="border-accent flex size-14 flex-col items-center justify-center rounded border"
  >
    <span class="text-foreground font-semibold">{weight}</span>
    <span class="text-muted-foreground text-xs">{weightUnit}</span>
  </div>
  <div class="flex w-full flex-1 flex-col gap-2">
    <span class="text-lg font-bold">{name}</span>
    <span class="text-muted-foreground text-sm">{sets} sets, {reps} reps</span>
  </div>
</div>
