// src/lib/components/features/workout/ExerciseDrawer.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Drawer, Field, Input, Label, Select } from "../../ui";
  import { type WeightUnit } from "$lib/db";
  import { WeightUnitSelect } from "$lib/components/shared";

  type Props = {
    onWeightChange: (weight: number) => void;
    onSetsChange: (sets: number) => void;
    onRepsChange: (reps: number) => void;
    onWeightUnitChange: (unit: WeightUnit) => void;
    defaultWeight: number;
    defaultSets: number;
    defaultReps: number;
    defaultWeightUnit: WeightUnit;
    instructions?: string[];
    name: string;
    open: boolean;
    onOpenChange?: (open: boolean) => void;
  };

  let {
    onWeightChange,
    onSetsChange,
    onRepsChange,
    onWeightUnitChange,
    defaultWeight,
    defaultWeightUnit,
    defaultSets,
    defaultReps,
    instructions,
    name,
    open = $bindable(false),
    onOpenChange,
  }: Props = $props();
  let init = $state(false);

  $effect(() => {
    if (!init) return;
    onOpenChange?.(open);
  });

  onMount(() => {
    init = true;
  });
</script>

<Drawer bind:open title={name}>
  <div class="flex flex-col gap-4">
    <div class="flex w-full items-center gap-4">
      <Field class="w-3/4">
        <Label for="weight">Weight</Label>
        <Input
          id="weight"
          defaultValue={defaultWeight}
          type="number"
          step={0.5}
          inputmode="decimal"
          oninput={(e) => onWeightChange(parseInt(e.currentTarget.value))}
        />
      </Field>
      <Field class="w-1/4">
        <Label for="unit">Unit</Label>
        <WeightUnitSelect
          id="unit"
          value={defaultWeightUnit}
          onchange={(unit) => onWeightUnitChange(unit)}
        />
      </Field>
    </div>
    <Field>
      <Label for="sets">Sets</Label>
      <Select
        id="sets"
        value={defaultSets}
        onchange={(e) => onSetsChange(parseInt(e.currentTarget.value))}
      >
        {#each { length: 10 }, idx}
          <option value={idx + 1}>{idx + 1}</option>
        {/each}
      </Select>
    </Field>
    <Field>
      <Label>Reps</Label>
      <Select
        value={defaultReps}
        onchange={(e) => onRepsChange(parseInt(e.currentTarget.value))}
      >
        {#each { length: 30 }, idx}
          <option value={idx + 1}>{idx + 1}</option>
        {/each}
      </Select>
    </Field>
  </div>
  {#if instructions && instructions.length > 0}
    <details style="display: flex; flex-direction: column; gap: var(--size-2);">
      <summary
        style="color: var(--color-muted-foreground)"
        class="text-sm tracking-wide uppercase">instructions</summary
      >
      <ol class="flex flex-col gap-2 p-2">
        {#each instructions as instruction, idx}
          <li class="text-lg">
            <span>{idx + 1}.</span>
            {instruction}
          </li>
        {/each}
      </ol>
    </details>
  {/if}
</Drawer>

// src/lib/components/features/workout/ExerciseDrawer.tsx
import type { WeightUnit } from "$lib/db";
import { Field, Input, Select, type SelectProps } from "$lib/eb";
import { InstructionsList, Sheet, WeightUnitSelect } from "../../shared";

const range = (count: number): SelectProps["items"] =>
  Array.from({ length: count }, (_, idx) => ({
    label: String(idx + 1),
    value: String(idx + 1),
  }));

const setOptions = range(10);
const repOptions = range(30);

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  name: string;
  instructions?: string[];
  defaultWeight: number;
  defaultWeightUnit: WeightUnit;
  defaultSets: number;
  defaultReps: number;
  onWeightChange: (weight: number) => void;
  onWeightUnitChange: (unit: WeightUnit) => void;
  onSetsChange: (sets: number) => void;
  onRepsChange: (reps: number) => void;
};

export function ExerciseDrawer({
  open,
  onOpenChange,
  name,
  instructions,
  defaultWeight,
  defaultWeightUnit,
  defaultSets,
  defaultReps,
  onWeightChange,
  onWeightUnitChange,
  onSetsChange,
  onRepsChange,
}: Props) {
  return (
    <Sheet open={open} onOpenChange={onOpenChange} title={name}>
      <div className="flex items-end gap-3">
        <Field className="flex-1">
          <Field.Label>Weight</Field.Label>
          <Input
            type="number"
            min={0}
            step={0.5}
            inputMode="decimal"
            defaultValue={defaultWeight}
            onChange={(event) => {
              const weight = Number(event.currentTarget.value);
              if (!Number.isNaN(weight)) onWeightChange(weight);
            }}
          />
        </Field>
        <WeightUnitSelect
          className="w-28"
          label="Unit"
          value={defaultWeightUnit}
          onValueChange={onWeightUnitChange}
        />
      </div>
      <div className="grid grid-cols-2 gap-3">
        <Select
          label="Sets"
          items={setOptions}
          defaultValue={String(defaultSets)}
          onValueChange={(sets) => sets && onSetsChange(Number(sets))}
        />
        <Select
          label="Reps"
          items={repOptions}
          defaultValue={String(defaultReps)}
          onValueChange={(reps) => reps && onRepsChange(Number(reps))}
        />
      </div>
      {instructions && instructions.length > 0 && (
        <details className="group mt-2">
          <summary className="text-accent cursor-pointer font-semibold">Instructions</summary>
          <div className="pt-3">
            <InstructionsList instructions={instructions} />
          </div>
        </details>
      )}
    </Sheet>
  );
}
