// src/WorkoutCard.svelte
<script lang="ts">
    type Props = {
            workoutName: string;
            exercises: string[];
    };
    let { workoutName, exercises }: Props = $props();
    const DISPLAY_COUNT = 3;
    const overflowCount = $derived(exercises.length - DISPLAY_COUNT);
</script>

<div class="container">
    <h3>{workoutName}</h3>
    <footer>
        <div>
            <div>
                <span class="exercise-count">
                    {exercises.length}
                </span>
                <span class="exercise-count-label">
                    Exercises
                </span>
            </div>
            {#each exercises.slice(0, DISPLAY_COUNT) as exercise}
                <div class="exercise-name">
                    {exercise}
                </div>
            {/each}
        </div>
        <div class="overflow-container">
            {#if overflowCount > 0}
                <div class="overflow-count">
                    <span>+ {overflowCount} more</span>
                </div>
            {/if}
        </div>
    </footer>
</div>

<style>
    h3, footer {
        padding: var(--size-1) var(--size-2);
    }

    footer {
        display: flex;
        justify-content: space-between;
        flex-direction: row;
        gap: var(--size-4);
    }

    .container {
        border-radius: 8px;
        border: 1px solid black;
        max-width: var(--max-width, 300px);
    }

    .exercise-name {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        max-width: 175px;
    }

    .exercise-count {
        font-weight: 600;
    }

    .exercise-count-label {
        font-weight: 500;
        text-transform: uppercase;
        font-size: x-small;
    }

    .overflow-container {
        margin-top: auto;
    }

    .overflow-count {
        border-radius: 9999px;
        padding: var(--size-1) var(--size-2);
        font-size: small;
        border: 1px solid black;
        width: fit-content;
    }
</style>

// src/lib/components/features/workout/WorkoutCard.tsx
import { Card } from "$lib/eb";

const DISPLAY_COUNT = 3;

type Props = {
  workoutName: string;
  exercises: string[];
};

export function WorkoutCard({ workoutName, exercises }: Props) {
  const overflowCount = exercises.length - DISPLAY_COUNT;

  return (
    <Card>
      <Card.Header>
        <Card.Title>{workoutName}</Card.Title>
      </Card.Header>
      <Card.Content>
        <ul className="flex flex-col gap-2">
          {exercises.slice(0, DISPLAY_COUNT).map((exercise) => (
            <li key={exercise}>{exercise}</li>
          ))}
          {overflowCount > 0 && (
            <li className="flex items-center justify-between">
              <span>…</span>
              <span className="border-muted rounded-pill border px-2 py-0.5 text-xs font-semibold">
                +{overflowCount} more
              </span>
            </li>
          )}
        </ul>
      </Card.Content>
    </Card>
  );
}
