// src/lib/components/page/Navbar.tsx
import { Button } from "$lib/eb";
import { ArrowLeftIcon, CheckIcon } from "@phosphor-icons/react";
import { useNavigate } from "@tanstack/react-router";
import type { ReactNode } from "react";

type Props = {
  /** Where the back button goes; no back button when omitted */
  backHref?: string;
  /** Show the back button as a primary "done" check */
  backAsComplete?: boolean;
  children?: ReactNode;
};

export function Navbar({ backHref, backAsComplete = false, children }: Props) {
  const navigate = useNavigate();

  return (
    <nav className="border-muted bg-background fixed inset-x-0 bottom-0 z-10 flex items-center gap-3 border-t pt-2 pr-[calc(var(--safe-right)+0.5rem)] pb-[var(--safe-bottom)] pl-[calc(var(--safe-left)+0.5rem)]">
      {backHref && (
        <Button
          iconOnly
          variant={backAsComplete ? "primary" : "secondary"}
          aria-label={backAsComplete ? "Done" : "Back"}
          onClick={() => navigate({ href: backHref })}
        >
          {backAsComplete ? <CheckIcon /> : <ArrowLeftIcon />}
        </Button>
      )}
      {children}
    </nav>
  );
}

// src/lib/components/page/Navbar.svelte
<script lang="ts">
  import type { SvelteHTMLElements } from "svelte/elements";
  import { goto } from "$app/navigation";
  import { ArrowLeftIcon, CheckIcon } from "phosphor-svelte";

  type Props = SvelteHTMLElements["nav"] & {
    backHref?: string;
    backAsComplete?: boolean;
  };

  let { children, backHref, backAsComplete = false }: Props = $props();
</script>

{#snippet backButton(href: string, asComplete?: boolean)}
  <button
    class="border-muted-foreground text-muted-foreground flex size-11 min-h-11 min-w-11 items-center justify-center rounded border"
    onclick={() => goto(href)}
    style={asComplete
      ? "background-color: var(--color-primary); color: var(--color-primary-foreground)"
      : ""}
  >
    {#if asComplete}
      <CheckIcon />
    {:else}
      <ArrowLeftIcon />
    {/if}
  </button>
{/snippet}

<nav
  class="bg-surface inset-x-0 bottom-0 rounded border-t border-white/10 shadow"
>
  {#if backHref}
    {@render backButton(backHref, backAsComplete)}
  {/if}
  {@render children?.()}
</nav>

<style>
  nav {
    display: flex;
    position: fixed;
    align-items: center;
    gap: var(--size-3);
    z-index: var(--layer-3);
    padding-top: var(--size-2);
    padding-right: calc(var(--size-3) + var(--safe-right));
    padding-bottom: var(--safe-bottom);
    padding-left: calc(var(--size-3) + var(--safe-left));
  }

  :global(:root) {
    /* safe area + button height + padding-bottom + padding-top */
    --navbar-height: calc(var(--safe-bottom) + 44px + 5px + 5px);
  }
</style>
