// src/lib/components/page/PageHeader.tsx
import { Display } from "$lib/eb";
import type { ReactNode } from "react";

type Props = {
  title?: string;
  /** Icon buttons shown beside the title */
  actions?: ReactNode;
  /** Shown below the title, e.g. search and filters */
  children?: ReactNode;
};

export function PageHeader({ title, actions, children }: Props) {
  return (
    <header className="bg-background/90 sticky top-0 z-10 -mx-4 flex flex-col gap-3 px-4 pt-[calc(var(--safe-top)+0.75rem)] pb-3 backdrop-blur-md">
      {(title || actions) && (
        <div className="flex items-center gap-2">
          {title && (
            // Title Case rather than Display's all caps
            <Display level={3} as="h1" className="min-w-0 flex-1 capitalize">
              {title}
            </Display>
          )}
          {actions && <div className="ml-auto flex items-center gap-1">{actions}</div>}
        </div>
      )}
      {children}
    </header>
  );
}

// src/lib/components/page/PageHeader.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { SvelteHTMLElements } from "svelte/elements";

  type Props = SvelteHTMLElements["HTMLHeadingElement"] & {
    title?: string | string[];
    level?: 1 | 2;
    right?: Snippet;
  };

  let { title, children, right }: Props = $props();
</script>

<header class="bg-background border-divide border-b shadow">
  {#if title || right}
    <div class="top-content">
      {#if title}
        <h1
          class="font-display text-foreground text-3xl font-bold tracking-wide"
        >
          {title}
        </h1>
      {/if}
      {#if right}
        <div class="right">{@render right()}</div>
      {/if}
    </div>
  {/if}
  {#if children}
    <div class="bottom-content">
      {@render children?.()}
    </div>
  {/if}
</header>

<style>
  header {
    position: sticky;
    top: 0;
    backdrop-filter: blur(10px);
    margin-right: var(--size-000);
    margin-left: var(--size-000);
    padding-top: calc(var(--safe-top) + var(--size-2));
    padding-right: var(--size-3);
    padding-bottom: var(--size-2);
    padding-left: var(--size-3);
  }

  .top-content {
    display: flex;
    align-items: baseline;
  }

  .bottom-content {
    display: flex;
    flex-direction: column;
    gap: var(--size-2);
    width: 100%;
  }

  .right {
    display: flex;
    align-items: baseline;
    gap: var(--size-4);
    margin-left: auto;
  }
</style>
