// src/lib/components/ExerciseSelectList.svelte
<script lang="ts">
  import { impactFeedback } from "@tauri-apps/plugin-haptics";
  import {
    IconCircle,
    IconCircleCheckFilled,
    IconInfoCircle,
  } from "@tabler/icons-svelte";

  type Props = {
    options: { value: string; label: string }[];
    onAdd?: (value: string) => void;
    onRemove?: (value: string) => void;
    onSelectInfo?: (value: string) => void;
    selected?: string[];
  };

  let {
    options,
    onAdd,
    onRemove,
    onSelectInfo,
    selected = $bindable([]),
  }: Props = $props();

  function handleSelect(option: Props["options"][0]) {
    selected.push(option.value);
    onAdd?.(option.value);
    impactFeedback("soft");
  }

  function handleRemove(option: Props["options"][0]) {
    selected = selected.filter((value) => value !== option.value);
    onRemove?.(option.value);
    impactFeedback("soft");
  }
</script>

<ul>
  {#each options as option}
    <li>
      {#if selected.includes(option.value)}
        <button onclick={() => handleRemove(option)}>
          <span>
            <IconCircleCheckFilled color="var(--primary)" />
          </span>
          {option.label}
        </button>
      {:else}
        <button onclick={() => handleSelect(option)}>
          <span>
            <IconCircle color="var(--primary)" />
          </span>
          {option.label}
        </button>
      {/if}
      <button
        style="margin-left: auto; width: fit-content; color: var(--muted-foreground)"
        onclick={() => onSelectInfo?.(option.value)}
      >
        <IconInfoCircle />
      </button>
    </li>
  {/each}
</ul>

<style>
  li:not(:first-child) {
    border-top: 1px solid var(--border-color);
  }
  ul {
    width: 100%;
  }
  li {
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 100%;
    list-style: none outside;

    button {
      display: flex;
      align-items: center;
      gap: var(--size-2);
      padding: var(--size-3) var(--size-2);
      width: 100%;
      color: var(--foreground);
    }
  }
</style>

// src/lib/components/shared/ExerciseSelectList.tsx
import { Button } from "$lib/eb";
import { CheckCircleIcon, CircleIcon, InfoIcon } from "@phosphor-icons/react";
import { impactFeedback } from "@tauri-apps/plugin-haptics";

type Option = { value: string; label: string };

type Props = {
  options: Option[];
  selected: string[];
  onAdd: (value: string) => void;
  onRemove: (value: string) => void;
  onSelectInfo: (value: string) => void;
};

function haptic() {
  // No haptics outside the native app
  impactFeedback("soft").catch(() => {});
}

export function ExerciseSelectList({
  options,
  selected,
  onAdd,
  onRemove,
  onSelectInfo,
}: Props) {
  return (
    <ul className="divide-muted divide-y">
      {options.map((option) => {
        const isSelected = selected.includes(option.value);

        return (
          <li key={option.value} className="flex items-center gap-2">
            <button
              type="button"
              aria-pressed={isSelected}
              className="flex flex-1 cursor-pointer items-center gap-3 py-3 text-left text-base"
              onClick={() => {
                if (isSelected) {
                  onRemove(option.value);
                } else {
                  onAdd(option.value);
                }
                haptic();
              }}
            >
              {isSelected ? (
                <CheckCircleIcon
                  weight="fill"
                  className="text-accent shrink-0"
                />
              ) : (
                <CircleIcon className="text-muted-foreground shrink-0" />
              )}
              {option.label}
            </button>
            <Button
              variant="ghost"
              iconOnly
              aria-label={`About ${option.label}`}
              className="text-muted-foreground"
              onClick={() => onSelectInfo(option.value)}
            >
              <InfoIcon />
            </Button>
          </li>
        );
      })}
    </ul>
  );
}
