// src/lib/components/shared/WeightUnitSelect.tsx
import { weightUnitSchema, type WeightUnit } from "$lib/db";
import { Select, type SelectProps } from "$lib/eb";

const items: SelectProps["items"] = [
  { label: "lbs", value: "lbs" },
  { label: "kg", value: "kg" },
];

type Props = Omit<SelectProps, "items" | "value" | "onValueChange"> & {
  value: WeightUnit;
  onValueChange: (unit: WeightUnit) => void;
};

export function WeightUnitSelect({ value, onValueChange, ...props }: Props) {
  return (
    <Select
      {...props}
      items={items}
      value={value}
      onValueChange={(unit) => {
        if (unit) onValueChange(weightUnitSchema.parse(unit));
      }}
    />
  );
}

// src/lib/components/shared/WeightUnitSelect.svelte
<script lang="ts">
  import type { ComponentProps } from "svelte";
  import { Select } from "../ui";
  import { weightUnitSchema, type WeightUnit } from "$lib/db";
  type Props = Omit<ComponentProps<typeof Select>, "value" | "onchange"> & {
    value: WeightUnit;
    onchange: (unit: WeightUnit) => void;
  };

  let { value = $bindable(), onchange, ...props }: Props = $props();
</script>

<Select
  bind:value
  onchange={(e) => {
    onchange?.(weightUnitSchema.parse(e.currentTarget.value));
  }}
  {...props}
>
  <option value="lbs">lbs</option>
  <option value="kg">kg</option>
</Select>
