// src/routes/[workoutId]/exercises/+page.svelte
<script lang="ts">
  import {
    Navbar,
    Input,
    ExerciseSelectList,
    Page,
    PageHeader,
    Tabs,
    ExerciseSelectFilters,
  } from "$lib/components";
  import { page } from "$app/state";
  import { InstructionsDrawerSelect } from "$lib/components";
  import { liveQuery } from "dexie";
  import { db } from "$lib/db";
  import { ExerciseSearch } from "$lib/state";
  import { getDefaultWeightUnit } from "$lib/utils";

  let { data } = $props();

  let selectedOnly = $state(false);

  let exerciseDetails:
    | { id: string; name: string; instructions: string[] }
    | undefined = $state({
    id: "",
    name: "",
    instructions: [],
  });

  let showDrawer = $state(false);

  let workoutExercises = liveQuery(() => {
    return db.workoutExercises
      .where("workoutId")
      .equals(page.params.workoutId)
      .toArray();
  });

  const exerciseSearch = new ExerciseSearch(data.allExercises);

  let selectedExerciseDetails = $derived.by(() => {
    return data.allExercises.filter((exercise) =>
      $workoutExercises?.map((e) => e.exerciseId).includes(exercise.id),
    );
  });

  let exerciseOptions = $derived.by(() => {
    const options = selectedOnly
      ? selectedExerciseDetails
      : exerciseSearch.filteredOptions;

    return options.map((exercise) => ({
      value: exercise.id,
      label: exercise.name,
    }));
  });

  function getExerciseDetailsFromId(id: string) {
    exerciseDetails = data.allExercises.find((exercise) => exercise.id === id);
  }

  const handleAddExercise = (value: string) => {
    const exercise = data.allExercises.find(
      (exercise) => exercise.id === value,
    );

    if (!exercise) return;

    db.workoutExercises.add({
      name: exercise.name,
      workoutId: page.params.workoutId,
      exerciseId: exercise.id,
      weight: 40,
      sets: 3,
      count: 10,
      order: $workoutExercises?.length ?? 0,
      weightUnit: getDefaultWeightUnit(),
      countUnit: "reps",
    });
  };

  const handleRemoveExercise = (value: string) => {
    db.workoutExercises.where("exerciseId").equals(value).delete();
  };
</script>

<Page>
  <PageHeader>
    <Input
      bind:value={exerciseSearch.term}
      type="search"
      placeholder="Search for an exercise..."
    />
    <Tabs
      defaultValue={selectedOnly}
      onChange={(value) => (selectedOnly = value)}
      options={[
        {
          label: "All",
          value: false,
        },
        {
          label: `Selected (${$workoutExercises?.length})`,
          value: true,
        },
      ]}
    />
  </PageHeader>

  <ExerciseSelectList
    selected={$workoutExercises?.map((exercise) => exercise.exerciseId)}
    options={exerciseOptions}
    onAdd={(value) => {
      handleAddExercise(value);
    }}
    onRemove={(value) => {
      handleRemoveExercise(value);
    }}
    onSelectInfo={(value) => {
      getExerciseDetailsFromId(value);
      showDrawer = true;
    }}
  />
</Page>

<Navbar
  backHref={`/${page.params.workoutId}`}
  backAsComplete={page.url.searchParams.has("complete")}
>
  <ExerciseSelectFilters
    muscleOptions={data.allMuscles}
    equipmentOptions={data.allEquipment}
    bind:selectedMuscles={exerciseSearch.muscleIds}
    bind:selectedEquipment={exerciseSearch.equipmentIds}
  />
</Navbar>
{#if exerciseDetails}
  <InstructionsDrawerSelect
    bind:open={showDrawer}
    name={exerciseDetails.name}
    exerciseId={exerciseDetails.id}
    isSelected={$workoutExercises
      ?.map((e) => e.exerciseId)
      .includes(exerciseDetails.id)}
    instructions={exerciseDetails.instructions}
    onAddExercise={handleAddExercise}
    onRemoveExercise={handleRemoveExercise}
  />
{/if}

// src/routes/$workoutId/exercises.tsx
import {
  EmptyMessage,
  ExerciseSelectFilters,
  ExerciseSelectList,
  InstructionsDrawerSelect,
  Navbar,
  Page,
  PageHeader,
} from "$lib/components";
import { db } from "$lib/db";
import { Input, SegmentedControl } from "$lib/eb";
import { useExerciseSearch } from "$lib/state";
import { getDefaultWeightUnit } from "$lib/utils";
import { createFileRoute, getRouteApi } from "@tanstack/react-router";
import { useLiveQuery } from "dexie-react-hooks";
import { useMemo, useState } from "react";

type Search = {
  /** Show the back button as "done" (coming from workout creation) */
  complete?: boolean;
};

// Exercise data is loaded once by the parent /$workoutId route
const workoutRoute = getRouteApi("/$workoutId");

export const Route = createFileRoute("/$workoutId/exercises")({
  validateSearch: (search: Record<string, unknown>): Search => ({
    complete: search.complete === true || search.complete === "true" ? true : undefined,
  }),
  component: ExerciseSelection,
});

function ExerciseSelection() {
  const { workoutId } = Route.useParams();
  const { complete } = Route.useSearch();
  const { allExercises, allMuscles, allEquipment } = workoutRoute.useLoaderData();

  const search = useExerciseSearch(allExercises);
  const [view, setView] = useState<"all" | "selected">("all");
  const [infoId, setInfoId] = useState<string | null>(null);
  const [infoOpen, setInfoOpen] = useState(false);

  const workoutExercises = useLiveQuery(
    () => db.workoutExercises.where("workoutId").equals(workoutId).toArray(),
    [workoutId],
  );

  const selectedIds = useMemo(
    () => workoutExercises?.map((e) => e.exerciseId) ?? [],
    [workoutExercises],
  );

  const options = useMemo(() => {
    const exercises =
      view === "selected"
        ? allExercises.filter((e) => selectedIds.includes(e.id))
        : search.filteredOptions;
    return exercises.map((e) => ({ value: e.id, label: e.name }));
  }, [view, allExercises, selectedIds, search.filteredOptions]);

  const infoExercise = allExercises.find((e) => e.id === infoId);

  function addExercise(exerciseId: string) {
    const exercise = allExercises.find((e) => e.id === exerciseId);
    if (!exercise) return;

    db.workoutExercises.add({
      name: exercise.name,
      workoutId,
      exerciseId: exercise.id,
      weight: 40,
      sets: 3,
      count: 10,
      order: workoutExercises?.length ?? 0,
      weightUnit: getDefaultWeightUnit(),
      countUnit: "reps",
    });
  }

  function removeExercise(exerciseId: string) {
    db.workoutExercises.where({ workoutId, exerciseId }).delete();
  }

  return (
    <Page>
      <PageHeader>
        <Input
          type="search"
          aria-label="Search exercises"
          placeholder="Search exercises"
          value={search.term}
          onChange={(event) => search.setTerm(event.currentTarget.value)}
        />
        <SegmentedControl
          aria-label="Show"
          className="w-full [&>*]:flex-1"
          value={view}
          onValueChange={(value) => setView(value as "all" | "selected")}
          options={[
            { value: "all", label: "All" },
            { value: "selected", label: `Selected (${selectedIds.length})` },
          ]}
        />
      </PageHeader>

      {options.length === 0 && (
        <EmptyMessage
          header={view === "selected" ? "No exercises selected." : "No matches."}
          message={
            view === "selected"
              ? "Pick exercises from the All tab."
              : "Try another search or clear the filters."
          }
        />
      )}
      <ExerciseSelectList
        options={options}
        selected={selectedIds}
        onAdd={addExercise}
        onRemove={removeExercise}
        onSelectInfo={(id) => {
          setInfoId(id);
          setInfoOpen(true);
        }}
      />

      <Navbar backHref={`/${workoutId}`} backAsComplete={complete}>
        <ExerciseSelectFilters
          muscleOptions={allMuscles}
          equipmentOptions={allEquipment}
          selectedMuscles={search.muscleIds}
          selectedEquipment={search.equipmentIds}
          onMusclesChange={search.setMuscleIds}
          onEquipmentChange={search.setEquipmentIds}
        />
      </Navbar>

      {infoExercise && (
        <InstructionsDrawerSelect
          open={infoOpen}
          onOpenChange={setInfoOpen}
          name={infoExercise.name}
          exerciseId={infoExercise.id}
          instructions={infoExercise.instructions}
          isSelected={selectedIds.includes(infoExercise.id)}
          onAddExercise={addExercise}
          onRemoveExercise={removeExercise}
        />
      )}
    </Page>
  );
}
