// src/lib/components/features/history/HistoryCard.tsx
import { Card } from "$lib/eb";
import { dateDifferenceInMinutes, dateFormatter } from "$lib/utils";
import { BarbellIcon, ClockIcon } from "@phosphor-icons/react";

type Props = {
  startTime: Date;
  endTime?: Date;
  workoutName?: string;
  tonnage: number;
};

export function HistoryCard({
  startTime,
  endTime,
  workoutName,
  tonnage,
}: Props) {
  return (
    <Card>
      <Card.Header>
        {workoutName && (
          <span className="text-muted-foreground">{workoutName}</span>
        )}
        <Card.Title>
          <time dateTime={new Date(startTime).toISOString()}>
            {dateFormatter.format(new Date(startTime))}
          </time>
        </Card.Title>
      </Card.Header>
      <Card.Content className="flex items-center justify-between">
        <Stat icon={<BarbellIcon size={16} />}>
          {Math.round(tonnage).toLocaleString()} lbs
        </Stat>
        {endTime && (
          <Stat icon={<ClockIcon size={16} />}>
            {dateDifferenceInMinutes(startTime, endTime)} min
          </Stat>
        )}
      </Card.Content>
    </Card>
  );
}

function Stat({
  icon,
  children,
}: {
  icon: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <span className="flex items-center gap-2">
      {icon}
      <span className="text-foreground font-semibold">{children}</span>
    </span>
  );
}

// src/lib/components/features/history/HistoryCard.svelte
<script lang="ts">
  import { dateDifferenceInMinutes, dateFormatter } from "$lib/utils";
  import { BarbellIcon, ClockIcon } from "phosphor-svelte";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = HTMLAttributes<HTMLElement> & {
    startTime: Date;
    endTime?: Date;
    workoutName?: string;
    tonnage: number;
  };

  let { startTime, endTime, tonnage, workoutName, ...props }: Props = $props();
</script>

<section
  {...props}
  class={[
    props.class,
    "border-border bg-surface text-foreground flex flex-col gap-3 rounded-sm border px-3 py-2 shadow",
  ]}
>
  <header class=" flex items-baseline justify-between text-lg font-bold">
    <time>{dateFormatter.format(new Date(startTime))}</time>
    {#if workoutName}
      <span class="text-muted-foreground text-sm">{workoutName}</span>
    {/if}
  </header>
  <div>
    <span>
      <BarbellIcon size={16} />
      <span class="count">{tonnage}</span>
      lbs
    </span>
    {#if endTime}
      <span>
        <ClockIcon size={16} />
        <time class="count">{dateDifferenceInMinutes(startTime, endTime)}</time>
        min.
      </span>
    {/if}
  </div>
</section>

<style>
  div {
    display: flex;
    justify-content: space-between;
    align-items: center;

    span {
      display: flex;
      align-items: center;
      gap: var(--size-2);
    }

    .count {
      font-weight: var(--font-weight-7);
    }

    time {
      font-weight: var(--font-weight-7);
    }
  }
</style>
