// src/routes/[workoutId]/history/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { page } from "$app/state";
  import { BusinessClipboard } from "$lib/assets";
  import { EmptyMessage, HistoryCard, Page, PageHeader } from "$lib/components";
  import Navbar from "$lib/components/page/Navbar.svelte";
  import { db } from "$lib/db";
  import { calculateTonnagePerAttribute } from "$lib/utils";
  import { liveQuery } from "dexie";

  let workout = liveQuery(() => db.workouts.get(page.params.workoutId));

  let history = liveQuery(() => {
    return db.history
      .where("workoutId")
      .equals(page.params.workoutId)
      .reverse()
      .sortBy("startTime");
  });
  let successSets = liveQuery(() => {
    return db.historySets
      .filter(
        (set) => $history.some((h) => h.id === set.historyId) && set.isSuccess,
      )
      .toArray();
  });

  let tonnage: Map<string, number> = $derived(
    calculateTonnagePerAttribute($successSets || [], (set) => set.historyId),
  );
</script>

<Page>
  <PageHeader title={$workout?.name}>
    {#snippet right()}
      <span>History</span>
    {/snippet}
  </PageHeader>
  {#if $history?.length === 0}
    <EmptyMessage
      header="No history yet."
      message="Past workout details will appear here."
    />
    <BusinessClipboard />
  {/if}
  <div class="space-y-8">
    {#each $history || [] as item}
      <HistoryCard
        onclick={() => {
          goto(`/${page.params.workoutId}/history/${item.id}`);
        }}
        startTime={item.startTime}
        endTime={item.endTime || undefined}
        tonnage={tonnage.get(item.id) || 0}
      />
    {/each}
  </div>
  <Navbar backHref="/{page.params.workoutId}" />
</Page>

// src/routes/$workoutId/history/index.tsx
import { BusinessClipboard } from "$lib/assets";
import { EmptyMessage, HistoryCard, Navbar, Page, PageHeader } from "$lib/components";
import { db } from "$lib/db";
import { calculateTonnagePerAttribute } from "$lib/utils";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useLiveQuery } from "dexie-react-hooks";
import { useMemo } from "react";

export const Route = createFileRoute("/$workoutId/history/")({
  component: WorkoutHistory,
});

function WorkoutHistory() {
  const { workoutId } = Route.useParams();

  const workout = useLiveQuery(() => db.workouts.get(workoutId), [workoutId]);
  const history = useLiveQuery(
    () => db.history.where("workoutId").equals(workoutId).reverse().sortBy("startTime"),
    [workoutId],
  );
  const successSets = useLiveQuery(async () => {
    const historyIds = (await db.history
      .where("workoutId")
      .equals(workoutId)
      .primaryKeys()) as string[];
    return db.historySets
      .where("historyId")
      .anyOf(historyIds)
      .filter((set) => set.isSuccess)
      .toArray();
  }, [workoutId]);

  const tonnage = useMemo(
    () => calculateTonnagePerAttribute(successSets ?? [], (s) => s.historyId),
    [successSets],
  );

  return (
    <Page>
      <PageHeader title={workout?.name}>
        <p className="text-accent font-semibold">History</p>
      </PageHeader>
      {history?.length === 0 && (
        <>
          <EmptyMessage header="No history yet." message="Past workout details will appear here." />
          <BusinessClipboard />
        </>
      )}
      <section className="flex flex-col gap-4">
        {history?.map((item) => (
          <Link
            key={item.id}
            to="/$workoutId/history/$historyId"
            params={{ workoutId, historyId: item.id }}
          >
            <HistoryCard
              startTime={item.startTime}
              endTime={item.endTime}
              tonnage={tonnage.get(item.id) ?? 0}
            />
          </Link>
        ))}
      </section>
      <Navbar backHref={`/${workoutId}`} />
    </Page>
  );
}
