// src/lib/components/features/workout/ExerciseDrawer.tsx
import type { WeightUnit } from "$lib/db";
import { Field, Input, Select, type SelectProps } from "$lib/eb";
import { InstructionsList, Sheet, WeightUnitSelect } from "../../shared";

const range = (count: number): SelectProps["items"] =>
  Array.from({ length: count }, (_, idx) => ({
    label: String(idx + 1),
    value: String(idx + 1),
  }));

const setOptions = range(10);
const repOptions = range(30);

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  name: string;
  instructions?: string[];
  defaultWeight: number;
  defaultWeightUnit: WeightUnit;
  defaultSets: number;
  defaultReps: number;
  onWeightChange: (weight: number) => void;
  onWeightUnitChange: (unit: WeightUnit) => void;
  onSetsChange: (sets: number) => void;
  onRepsChange: (reps: number) => void;
};

export function ExerciseDrawer({
  open,
  onOpenChange,
  name,
  instructions,
  defaultWeight,
  defaultWeightUnit,
  defaultSets,
  defaultReps,
  onWeightChange,
  onWeightUnitChange,
  onSetsChange,
  onRepsChange,
}: Props) {
  return (
    <Sheet open={open} onOpenChange={onOpenChange} title={name}>
      <div className="flex items-end gap-3">
        <Field className="flex-1">
          <Field.Label>Weight</Field.Label>
          <Input
            type="number"
            min={0}
            step={0.5}
            inputMode="decimal"
            defaultValue={defaultWeight}
            onChange={(event) => {
              const weight = Number(event.currentTarget.value);
              if (!Number.isNaN(weight)) onWeightChange(weight);
            }}
          />
        </Field>
        <WeightUnitSelect
          className="w-28"
          label="Unit"
          value={defaultWeightUnit}
          onValueChange={onWeightUnitChange}
        />
      </div>
      <div className="grid grid-cols-2 gap-3">
        <Select
          label="Sets"
          items={setOptions}
          defaultValue={String(defaultSets)}
          onValueChange={(sets) => sets && onSetsChange(Number(sets))}
        />
        <Select
          label="Reps"
          items={repOptions}
          defaultValue={String(defaultReps)}
          onValueChange={(reps) => reps && onRepsChange(Number(reps))}
        />
      </div>
      {instructions && instructions.length > 0 && (
        <details className="group mt-2">
          <summary className="text-accent cursor-pointer font-semibold">Instructions</summary>
          <div className="pt-3">
            <InstructionsList instructions={instructions} />
          </div>
        </details>
      )}
    </Sheet>
  );
}

// src/lib/components/ExerciseDrawer.svelte
<script lang="ts">
  import { Drawer, Input } from "./ui";

  type Props = {
    onWeightChange: (weight: number) => void;
    onSetsChange: (sets: number) => void;
    onRepsChange: (reps: number) => void;
    defaultWeight: number;
    defaultSets: number;
    defaultReps: number;
    instructions?: string[];
    name: string;
    open: boolean;
  };

  let {
    onWeightChange,
    onSetsChange,
    onRepsChange,
    defaultWeight,
    defaultSets,
    defaultReps,
    instructions,
    name,
    open = $bindable(false),
  }: Props = $props();
</script>

<Drawer bind:open title={name}>
  <div style="display: flex; gap: var(--size-4); flex-direction: column;">
    <label>
      <span>Weight (lbs)</span>
      <Input
        defaultValue={defaultWeight}
        type="number"
        step={0.5}
        inputmode="decimal"
        oninput={(e) => onWeightChange(parseInt(e.currentTarget.value))}
      />
    </label>
    <label>
      <span>Sets</span>
      <select
        value={defaultSets}
        onchange={(e) => onSetsChange(parseInt(e.currentTarget.value))}
      >
        {#each { length: 10 }, idx}
          <option value={idx + 1}>{idx + 1}</option>
        {/each}
      </select>
    </label>
    <label>
      <span>Reps</span>
      <select
        value={defaultReps}
        onchange={(e) => onRepsChange(parseInt(e.currentTarget.value))}
      >
        {#each { length: 30 }, idx}
          <option value={idx + 1}>{idx + 1}</option>
        {/each}
      </select>
    </label>
  </div>
  {#if instructions && instructions.length > 0}
    <details style="display: flex; flex-direction: column; gap: var(--size-2);">
      <summary style="color: var(--muted-foreground)">View instructions</summary
      >
      <ol
        style="margin-top: var(--size-4); line-height: var(--font-lineheight-3); color: var(--muted-foreground);"
      >
        {#each instructions as instruction, idx}
          <li>
            <span>{idx + 1}.</span>
            {instruction}
          </li>
        {/each}
      </ol>
    </details>
  {/if}
</Drawer>

<style>
  label {
    display: grid;
    gap: var(--size-2);
  }

  select {
    border: 1px solid var(--border-color);
    border-radius: var(--radius-3);
    background-color: transparent;
    padding: 12px 10px;
    color: var(--magnolia);
    font-weight: var(--font-weight);
    font-size: var(--font-size, var(--font-size-2));
  }

  select:focus {
    transition: all;
    outline: 2px solid var(--primary-color);
    outline-offset: 2px;
  }

  ol {
    display: flex;
    flex-direction: column;
    gap: var(--size-2);
    padding: var(--size-2);

    li {
      font-size: var(--font-size-2);
      line-height: var(--font-lineheight-4);
      span {
        font-weight: var(--font-weight-7);
      }
    }
  }
</style>
